subroutine part_flux_injection(istep,vxp,n,h,ntype,nmax,bcnd,sour_xy,&
     sour_xz,sour_fx_yz,nproc,iseed,flag_cex,np_tot,N_flx,nproc_mpi,&
     mpi_rank,nsav,P_loss)
!     ===================================================================
!     VERSION:         0.5
!     LAST MOD:      May/18
!     MOD AUTHOR:    G. Fubiani
!     COMMENTS:     
!     NOTES:    
!     -------------------------------------------------------------------
  use omp_lib
  use mpi
  implicit none
  include 'particle_info.h'
  include 'constants.h'
  integer ierr,mpi_rank,nproc_mpi,istep,n(3),nmax,ntype,iproc,nproc,&
       iseed(nproc),iseed_OMP,Nh,nsav,iy,iz,ptype
  integer:: bcnd(0:n(1)+2,0:n(2)+2,0:n(3)+2), &
       sour_xy(0:n(1)+2,0:n(2)+2,ntype,nproc),&
       sour_xz(0:n(1)+2,0:n(3)+2,ntype,nproc),&
       sour_fx_yz(0:n(2)+2,0:n(3)+2,ntype,nproc),&
       np_tot(ntype,nproc),flag_cex(nmax,nproc),N_flx(ntype,nproc)
  real(kind=8):: h(3),vxp(6,nmax,ntype,nproc),jH,ran2,rnd,dNh,Nh_tmp,k,&
       P_loss(4,ntype,nproc)
  integer,allocatable:: sour_tmp(:,:,:)
  character:: pnum*1

  ! Negative ion emmiter on the surface of the extraction electrode
  if(jne.gt.0.d0) then
     ! Initialization
     ptype= tag_neg
     jH= jne*10.d0 ! A/m-2

     ! Number of ions per MPI and OMP proc
     dNh= jH*Sg*(real(ns_flx)*dt)/(Nm(tag_neg)*qe)/real(nproc_mpi)/real(nproc)
     Nh_tmp= INT(dNh)

     ! Correct for round-off errors
     rnd= ran2(iseed(1))
     if( rnd.le.(dNh-Nh_tmp) ) Nh_tmp= Nh_tmp + 1
     N_flx(ptype,:)= Nh_tmp
  endif

  ! Thruster: define specie which will be injected
  if(flag_thr.eq.1) ptype= 1 ! Electrons

  !
  ! Load particles in parallel
  !
  !$OMP PARALLEL PRIVATE(iproc,iseed_OMP,Nh)
  ! Get processor id (from 0 to nproc-1)
  iproc= omp_get_thread_num() + 1
  iseed_OMP= iseed(iproc)

  ! Thruster: re-injected flux= electron - ion fluxes at the anode 
  if(flag_thr.eq.1) then
     Nh= N_flx(1,iproc) - SUM(N_flx(2:ntype,iproc)) ! sum over positive charges
     if(Nh.lt.0) goto 10 ! Next thread
  else 
     ! Negative ions
     Nh= N_flx(ptype,iproc)
  endif

  call load_flux_OMP(vxp,n,h,ntype,nmax,bcnd,sour_xy,sour_xz,sour_fx_yz,nproc,iseed_OMP,&
       flag_cex,np_tot,Nh,ptype,iproc,P_loss)

10  iseed(iproc)= iseed_OMP
  !$OMP END PARALLEL

  !
  ! Source term
  !
  if(MOD(istep,nsav).eq.1) then
     allocate( sour_tmp(0:n(2)+2,0:n(3)+2,ntype) )
     sour_tmp=0.d0
     call MPI_REDUCE(SUM(sour_fx_yz, DIM=4), sour_tmp, (n(2)+3)*(n(3)+3)*ntype, &
          MPI_INTEGER, MPI_SUM, 0,MPI_COMM_WORLD, ierr)

     if(mpi_rank.eq.0) then
        k=Nm(ptype)/(h(1)*h(2)*h(3))
        write (pnum,'(i1)'),ptype
        open(14,file='DATA/DATA_2D/sour_fx'//pnum//'_yz.mco')
        write(14,*) n(2),n(3)
        do iz=n(3)+1,1,-1 
           write(14,'(800(e18.6,1x))') ( real(sour_tmp(iy,iz,ptype))*k/(real(istep)*dt), iy=1,n(2)+1 )
        enddo
        close(14)
     endif

     deallocate( sour_tmp )
  endif

  !
  ! Write on screen
  !
  if( ptype.eq.tag_neg .and. istep.eq.1 .and. mpi_rank.eq.0 ) then
     print'(1x,"Negative ion current generated by neutral atoms on the extraction electrode: IH-(A)= ",&
          f8.3,", jH-(A/m2)= ",f6.1)',dNh*real(nproc*nproc_mpi)*qe*Nm(tag_neg)/(real(ns_flx)*dt),jH
  endif
  
  return
end subroutine part_flux_injection


subroutine  load_flux_OMP(vxp,n,h,ntype,nmax,bcnd,sour_xy,sour_xz,sour_fx_yz,&
     nproc,iseed,flag_cex,np_tot,Nh,ptype,iproc,P_loss)
!     ===================================================================
!     VERSION:         0.3
!     LAST MOD:      Dec/23
!     MOD AUTHOR:    G. Fubiani
!     COMMENTS:     
!     NOTES:    
!     -------------------------------------------------------------------
  implicit none
  include 'particle_info.h'
  include 'constants.h'
  integer:: n(3),nmax,ntype,ix,iy,iz,i,Nh,iproc,nproc,iseed,ptype
  integer:: bcnd(0:n(1)+2,0:n(2)+2,0:n(3)+2), &
       sour_xy(0:n(1)+2,0:n(2)+2,ntype,nproc),&
       sour_xz(0:n(1)+2,0:n(3)+2,ntype,nproc),&
       sour_fx_yz(0:n(2)+2,0:n(3)+2,ntype,nproc),&
       np_tot(ntype,nproc),np_tot_tmp,flag_cex(nmax,nproc)
  real(kind=8):: h(3),vxp(6,nmax,ntype,nproc),ran2,rnd(2),&
       x_inj,y_inj,z_inj,vt,vx,vy,vz,P_loss(4,ntype,nproc),dt_tmp

 ! Negative ions
  if(ptype.eq.tag_neg) then
     ! Particle flux off a surface 
     x_inj= xg1
     ix= INT( xg1/h(1) ) + 1
  endif

  ! Thruster
  if(flag_thr.eq.1) then
     x_inj= x_thr ! inject (artificially) behind the plasma sheath
     ix= ix_thr
  endif

  ! Loop over negative ions
  do i=1,Nh

90   rnd(1)= ran2(iseed)
     if(flag_thr.eq.1) then ! Thruster
        y_inj= (ymax-y_thr)/2.d0 + y_thr*rnd(1)
     else  ! Negative ions
        y_inj= (ymax-Lgy)/2.d0 + Lgy*rnd(1)
     endif
     iy= INT( y_inj/h(2) ) + 1

     rnd(1)= ran2(iseed)
     z_inj= (zmax-Lgz)/2.d0 + Lgz*rnd(1)
     iz= INT( z_inj/h(3) ) + 1

     ! Negative ions
     if(ptype.eq.tag_neg) then
        ! Load particle on the wall surface
        if( bcnd(ix,iy,iz).ge.1 .and. &
             bcnd(ix,iy+1,iz).ge.1 .and. &
             bcnd(ix,iy,iz+1).ge.1 .and. &
             bcnd(ix,iy+1,iz+1).ge.1 .and. &
             bcnd(ix+1,iy,iz).ge.1 .and. &         
             bcnd(ix+1,iy+1,iz).ge.1 .and. &
             bcnd(ix+1,iy,iz+1).ge.1 .and. &         
             bcnd(ix+1,iy+1,iz+1).ge.1 ) then
           continue
        else
           ! Do not load inside apertures
           goto 90
        endif
     endif
     
     ! Create ion
     np_tot(ptype,iproc)= np_tot(ptype,iproc) + 1
     np_tot_tmp= np_tot(ptype,iproc)

     ! Do not reset sour 
     sour_fx_yz(iy,iz,ptype,iproc)= sour_fx_yz(iy,iz,ptype,iproc) + 1
     if(iz.eq.iz_pl) &
          sour_xy(ix,iy,ptype,iproc)= sour_xy(ix,iy,ptype,iproc) + 1
     if(iy.eq.n(2)/2+1) &
          sour_xz(ix,iz,ptype,iproc)= sour_xz(ix,iz,ptype,iproc) + 1
          
     ! Gaussian loading (flux normal to the PE)
     vt= dsqrt(2.d0*qe*THm/ABS(mass(ptype))) 
     
     rnd(1)=ran2(iseed)
     vx = -vt*dsqrt( -dlog(1-rnd(1)) ) ! inject toward the LHS
     
     rnd(1)= ran2(iseed)
     rnd(2)= ran2(iseed)
     call load_gauss(vy,vz,vt,rnd)
     
     vxp(4,np_tot_tmp,ptype,iproc)= vx 
     vxp(5,np_tot_tmp,ptype,iproc)= vy
     vxp(6,np_tot_tmp,ptype,iproc)= vz

     rnd(1)= ran2(iseed)
     ! Spread the flux over ns_flx*dt
     dt_tmp= rnd(1)*(real(ns_flx)*dt)
     vxp(1,np_tot_tmp,ptype,iproc)= x_inj + vx*dt_tmp
     vxp(2,np_tot_tmp,ptype,iproc)= y_inj 
     vxp(3,np_tot_tmp,ptype,iproc)= z_inj
     
     P_loss(4,ptype,iproc)= P_loss(4,ptype,iproc) + &
          0.5d0*Nm(ptype)*mass(ptype)*( vx*vx + vy*vy + vz*vz ) 

     ! Flag for CEX collisions
     if(ptype.eq.tag_neg) flag_cex(np_tot_tmp,iproc)= tag_neu 
    
  enddo ! end-loop over Nh
  
  return
end subroutine load_flux_OMP
