!> ============================================================================
!>  mod_magneticField.f90  (adapted to your Config in mod_config)
!>
!>  Uses:
!>    - type(Config) from mod_config (arrays are fixed-size NBMAX)
!>
!>  Provides:
!>    - type(MagneticField) with methods:
!>        allocate_from_cfg(cfg, xmax, ymax, zmax)
!>        build_from_cfg(cfg, xmax, ymax, zmax, mpi_rank)
!>        compute_norm()
!>        write_macho_planes(out_dir, every, mpi_rank)
!>        get_Bi_pointer(ptr)
!>        get_Bmax()
!>
!>  Bi layout:
!>    Bi(1,:,:,:) = Bx [T]
!>    Bi(2,:,:,:) = By [T]
!>    Bi(3,:,:,:) = Bz [T]
!>    Bi(4,:,:,:) = |B|[T]
!>
!>  NOTE:
!>    read_Bfield_map() supports 2 common formats:
!>      (A) header line: nx ny nz  (or nx ny) then values
!>      (B) no header: raw values
!>    If your legacy Bx/By/Bz files differ, adjust that routine only.
!> ============================================================================
module mod_magneticField
  use, intrinsic :: iso_fortran_env, only: real64, int32
  use mod_config, only: Config, NBMAX
  use mod_domain, only: Domain
  implicit none
  private

  public :: MagneticField

  type :: MagneticField
     private
     integer(int32) :: n_B(3) = 0
     real(real64)   :: h_B(3) = 0.0_real64
     real(real64), pointer :: Bi(:,:,:,:) => null()
     real(real64) :: Bmax = 0.0_real64
     integer(int32) :: xBm(3) = 0
   contains
     procedure, public :: allocate_from_cfg
     procedure, public :: build_from_cfg
     procedure, public :: compute_norm
     procedure, public :: write_macho_planes
     procedure, public :: get_Bmax
     procedure, public :: get_Bi_pointer
     procedure, public :: destroy
  end type MagneticField

contains

  !> Allocate Bi using cfg%n_B if meaningful, else use cfg%n. Also sets h_B from xmax/ymax/zmax.
  subroutine destroy(self)
    class(MagneticField), intent(inout) :: self
    if (associated(self%Bi)) deallocate(self%Bi)
  end subroutine destroy


  subroutine allocate_from_cfg(self, cfg, dom)
    class(MagneticField), intent(inout) :: self
    type(Config),         intent(in)    :: cfg
    type(Domain),         intent(in)    :: dom
    integer :: nxB, nyB, nzB

    nxB = cfg%n_B(1); nyB = cfg%n_B(2); nzB = cfg%n_B(3)

    ! legacy behavior: if any <=1 => treat as no B grid map; still allocate 1-cell "dummy"
    if (nxB <= 1 .or. nyB <= 1 .or. nzB <= 1) then
       nxB = 1; nyB = 1; nzB = 1
    end if

    self%n_B = [nxB, nyB, nzB]

    if (associated(self%Bi)) deallocate(self%Bi)
    allocate(self%Bi(4, 0:nxB+2, 0:nyB+2, 0:nzB+2))
    self%Bi = 0.0_real64

    self%h_B = 0.0_real64
    if (nxB > 0) self%h_B(1) = dom%xmax / real(nxB, real64)
    if (nyB > 0) self%h_B(2) = dom%ymax / real(nyB, real64)
    if (nzB > 0) self%h_B(3) = dom%zmax / real(nzB, real64)

    self%Bmax = 0.0_real64
    self%xBm  = 0
  end subroutine allocate_from_cfg

  !> Build B using cfg%flag_B / cfg%nB / cfg%B_* arrays (legacy logic).
  subroutine build_from_cfg(self, cfg, dom, mpi_rank)
    class(MagneticField), intent(inout) :: self
    type(Config),         intent(in)    :: cfg
    type(Domain),         intent(in)    :: dom
    integer,              intent(in)    :: mpi_rank

    integer :: iB, B_dir
    character(len=20) :: base

    call self%allocate_from_cfg(cfg, dom)

    ! If no B requested, just keep zeros and return (still consistent for mover).
    if (cfg%flag_B == 0 .or. cfg%nB <= 0) then
       call self%compute_norm()
       return
    end if

    do iB = 1, min(cfg%nB, NBMAX)

       if (cfg%B_file(iB) == 's' .or. cfg%B_file(iB) == 'S') cycle

       base = cfg%B_name(iB)

       if (cfg%B_file(iB) == 'y' .or. cfg%B_file(iB) == 'Y') then
          ! external map files: <base>Bx.dat, <base>By.dat, <base>Bz.dat
          call read_Bfield_map(self%Bi, self%n_B, self%h_B, trim(base)//'Bx.dat', 1, cfg%B_scale(iB), mpi_rank)
          call read_Bfield_map(self%Bi, self%n_B, self%h_B, trim(base)//'By.dat', 2, cfg%B_scale(iB), mpi_rank)
          call read_Bfield_map(self%Bi, self%n_B, self%h_B, trim(base)//'Bz.dat', 3, cfg%B_scale(iB), mpi_rank)

       else if (cfg%B_file(iB) == 'n' .or. cfg%B_file(iB) == 'N') then

          call find_B_dir(cfg%B_info(iB), B_dir)

          if (mpi_rank == 0) then
             select case (base(1:1))
             case ('g','G'); write(*,*) 'Gaussian magnetic filter field profile'
             case ('p','P'); write(*,*) 'Magnetic filter field generated by a PG current (placeholder)'
             case ('e','E'); write(*,*) 'Cusp magnetic field profile (placeholder)'
             case ('t','T'); write(*,*) 'Hall thruster magnetic field profile (placeholder)'
             case default;   write(*,*) 'Unknown analytic B key: ', base(1:1)
             end select
          end if

          select case (base(1:1))
          case ('g','G')
             call gaussian_Bfield(self%Bi, self%n_B, self%h_B, cfg%B0(iB), cfg%x0(iB), cfg%dL(iB), cfg%B_info(iB))

          case ('p','P')
             call PG_current(self%Bi, self%n_B, self%h_B, cfg%B0(iB), B_dir)

          case ('e','E')
             call EE_magnets(self%Bi, self%n_B, self%h_B, cfg%B0(iB), cfg%x0(iB), cfg%z0(iB), cfg%dL(iB))

          case ('t','T')
             call Bfield_Hall_thruster(self%Bi, self%n_B, self%h_B, cfg%B0(iB), cfg%x0(iB), cfg%dL(iB))

          case default
             ! do nothing
          end select
       end if

    end do

    call self%compute_norm()
  end subroutine build_from_cfg

  !> Compute |B| and Bmax location
  subroutine compute_norm(self)
    class(MagneticField), intent(inout) :: self
    integer :: ix, iy, iz
    real(real64) :: bmag

    self%Bmax = 0.0_real64
    self%xBm  = 0

    do iz = lbound(self%Bi,4), ubound(self%Bi,4)
       do iy = lbound(self%Bi,3), ubound(self%Bi,3)
          do ix = lbound(self%Bi,2), ubound(self%Bi,2)
             bmag = sqrt(self%Bi(1,ix,iy,iz)**2 + self%Bi(2,ix,iy,iz)**2 + self%Bi(3,ix,iy,iz)**2)
             self%Bi(4,ix,iy,iz) = bmag
             if (bmag > self%Bmax) then
                self%Bmax = bmag
                self%xBm  = [ix, iy, iz]
             end if
          end do
       end do
    end do
  end subroutine compute_norm

  function get_Bmax(self) result(bmax)
    class(MagneticField), intent(in) :: self
    real(real64) :: bmax
    bmax = self%Bmax
  end function get_Bmax

  subroutine get_Bi_pointer(self, Bi_ptr)
    class(MagneticField), intent(in) :: self
    real(real64), pointer            :: Bi_ptr(:,:,:,:)
    Bi_ptr => self%Bi
  end subroutine get_Bi_pointer

  !> Writes same Macho-style planes as legacy (rank 0 only). Values in Gauss in files.
  subroutine write_macho_planes(self, out_dir, every, mpi_rank)
    class(MagneticField), intent(in) :: self
    character(len=*),     intent(in) :: out_dir
    integer,              intent(in) :: every
    integer,              intent(in) :: mpi_rank

    integer :: nxB, nyB, nzB
    integer :: ix, iy, iz, ix_pl
    character(len=512) :: f
    write(*,*) 'Writing B field planes in Macho format (rank 0 only)...'
    if (mpi_rank /= 0) return
    write(*,*) 'Output directory: ', trim(out_dir)
    nxB = self%n_B(1); nyB = self%n_B(2); nzB = self%n_B(3)
    write(*,*) 'B grid size: ', nxB, nyB, nzB
    if (nxB <= 1 .and. nyB <= 1 .and. nzB <= 1) return

    write(*,*) 'Bmax @ location:', self%xBm - 1

    ! XY plane (z mid)
    ! f = trim(out_dir)//'/B_xy.mco'
    ! open(30, file=f, status='replace')
    ! write(30,*) nxB/every, nyB/every
    ! do iy = nyB+1, 1, -every
    !    write(30,'(800(e18.6,1x))') ( self%Bi(4,ix,iy,nzB/2+1)*1.0e4_real64, ix=1, nxB+1, every )
    ! end do
    ! write(30,*) 'vector'
    ! do iy = nyB+1, 1, -every
    !    write(30,'(800(e18.6,1x))') ( atan2(self%Bi(2,ix,iy,nzB/2+1), self%Bi(1,ix,iy,nzB/2+1)), ix=1, nxB+1, every )
    ! end do
    ! close(30)

    f = trim(out_dir)//'/By_xy.mco'
    open(30, file=f, status='replace')
    write(30,*) nxB/every, nyB/every
    do iy = nyB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(2,ix,iy,nzB/2+1)*1.0e4_real64, ix=1, nxB+1, every )
    end do
    close(30)

    f = trim(out_dir)//'/Bx_xy.mco'
    open(30, file=f, status='replace')
    write(30,*) nxB/every, nyB/every
    do iy = nyB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(1,ix,iy,nzB/2+1)*1.0e4_real64, ix=1, nxB+1, every )
    end do
    close(30)

    ! XZ plane (y mid)
    f = trim(out_dir)//'/B_xz.mco'
    open(30, file=f, status='replace')
    write(30,*) nxB/every, nzB/every
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(4,ix,nyB/2+1,iz)*1.0e4_real64, ix=1, nxB+1, every )
    end do
    write(30,*) 'vector'
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( atan2(self%Bi(3,ix,nyB/2+1,iz), self%Bi(1,ix,nyB/2+1,iz)), ix=1, nxB+1, every )
    end do
    close(30)

    f = trim(out_dir)//'/Bx_xz.mco'
    open(30, file=f, status='replace')
    write(30,*) nxB/every, nzB/every
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(1,ix,nyB/2+1,iz)*1.0e4_real64, ix=1, nxB+1, every )
    end do
    close(30)

    f = trim(out_dir)//'/Bz_xz.mco'
    open(30, file=f, status='replace')
    write(30,*) nxB/every, nzB/every
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(3,ix,nyB/2+1,iz)*1.0e4_real64, ix=1, nxB+1, every )
    end do
    close(30)

    ! YZ plane (x mid)
    ix_pl = nxB/2 + 1

    f = trim(out_dir)//'/B_yz.mco'
    open(30, file=f, status='replace')
    write(30,*) nyB/every, nzB/every
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(4,ix_pl,iy,iz)*1.0e4_real64, iy=1, nyB+1, every )
    end do
    write(30,*) 'vector'
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( atan2(self%Bi(3,ix_pl,iy,iz), self%Bi(2,ix_pl,iy,iz)), iy=1, nyB+1, every )
    end do
    close(30)

    f = trim(out_dir)//'/By_yz.mco'
    open(30, file=f, status='replace')
    write(30,*) nyB/every, nzB/every
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(2,ix_pl,iy,iz)*1.0e4_real64, iy=1, nyB+1, every )
    end do
    close(30)

    f = trim(out_dir)//'/Bz_yz.mco'
    open(30, file=f, status='replace')
    write(30,*) nyB/every, nzB/every
    do iz = nzB+1, 1, -every
       write(30,'(800(e18.6,1x))') ( self%Bi(3,ix_pl,iy,iz)*1.0e4_real64, iy=1, nyB+1, every )
    end do
    close(30)
  end subroutine write_macho_planes


  ! ==========================================================================
  ! Private helper routines (legacy-like)
  ! ==========================================================================

  !> Determine B_dir from cfg%B_info(iB) (len=2 in your Config)
  subroutine find_B_dir(B_info, B_dir)
    character(len=*), intent(in)  :: B_info
    integer,          intent(out) :: B_dir

    if (index(B_info,'y')>0 .or. index(B_info,'Y')>0) then
       B_dir = 2
    else if (index(B_info,'z')>0 .or. index(B_info,'Z')>0) then
       B_dir = 3
    else
       B_dir = 1
    end if
  end subroutine find_B_dir

  !> Read external B map and accumulate into Bi(B_dir,:,:,:).
  subroutine read_Bfield_map(Bi, n_B, h_B, filename, B_dir, B_scale, mpi_rank)
    integer(int32), intent(in)  :: n_B(3)
    real(real64), intent(inout) :: Bi(4,0:n_B(1)+2,0:n_B(2)+2,0:n_B(3)+2)
    
    real(real64), intent(in)    :: h_B(3)
    character(len=*), intent(in) :: filename
    integer, intent(in)          :: B_dir
    real(real64), intent(in)     :: B_scale
    integer, intent(in)          :: mpi_rank

    integer :: ios, unit
    integer :: nx_in, ny_in, nz_in
    integer :: ix, iy, iz
    character(len=256) :: line
    logical :: has_header
    real(real64) :: val

    unit = 77
    open(unit, file=trim(filename), status='old', action='read', iostat=ios)
    if (ios /= 0) then
       if (mpi_rank == 0) write(*,*) 'ERROR: cannot open B map file: ', trim(filename)
       stop 1
    end if

    read(unit,'(A)', iostat=ios) line
    if (ios /= 0) then
       if (mpi_rank == 0) write(*,*) 'ERROR: empty B map file: ', trim(filename)
       stop 1
    end if

    nx_in = -1; ny_in = -1; nz_in = -1
    read(line, *, iostat=ios) nx_in, ny_in, nz_in
    if (ios == 0) then
       has_header = .true.
    else
       read(line, *, iostat=ios) nx_in, ny_in
       if (ios == 0) then
          nz_in = 1
          has_header = .true.
       else
          has_header = .false.
       end if
    end if

    if (.not. has_header) rewind(unit)

    do iz = 0, n_B(3)+2
       do iy = 0, n_B(2)+2
          do ix = 0, n_B(1)+2
             read(unit, *, iostat=ios) val
             if (ios /= 0) then
                if (mpi_rank == 0) then
                   write(*,*) 'ERROR reading map: ', trim(filename)
                   write(*,*) 'Stopped at ix,iy,iz = ', ix, iy, iz
                end if
                stop 1
             end if
             Bi(B_dir, ix, iy, iz) = Bi(B_dir, ix, iy, iz) + B_scale * val
          end do
       end do
    end do

    close(unit)
  end subroutine read_Bfield_map

  !> Gaussian field along chosen component B_dir
  subroutine gaussian_Bfield(Bi, n_B, h_B, B0, x0, dL, B_info)
    integer(int32), intent(in)  :: n_B(3)
    real(real64), intent(inout) :: Bi(4,0:n_B(1)+2,0:n_B(2)+2,0:n_B(3)+2)
    real(real64), intent(in)    :: h_B(3)
    real(real64), intent(in)    :: B0, x0, dL
    character, intent(in)         :: B_info

    integer :: ix, iy, iz
    integer :: B_dir
    real(real64) :: x, a, g

    if(B_info == 'By' .or. B_info == 'BY' .or. B_info == 'by') then
       B_dir = 2
    else if(B_info == 'Bz' .or. B_info == 'BZ' .or. B_info == 'bz') then
       B_dir = 3
    else
       B_dir = 1
    end if
    write(*,*) 'Gaussian B field along direction: ', B_dir
    write(*)
    if (dL <= 0.0_real64) return

    do iz = 0, n_B(3)+2
       do iy = 0, n_B(2)+2
          do ix = 0, n_B(1)+2
             x = real(ix-1, real64) * h_B(1)
             a = (x - x0)/dL
             g = exp(-(a*a))
             Bi(B_dir, ix, iy, iz) = Bi(B_dir, ix, iy, iz) + B0*exp(-(x-x0)**2/(2*dL**2))
          end do
       end do
    end do
  end subroutine gaussian_Bfield

  !> PG current (placeholder): smooth 1/(1+(x/L)^2) along B_dir
  subroutine PG_current(Bi, n_B, h_B, B0, B_dir)
    integer(int32), intent(in)  :: n_B(3)
    real(real64), intent(inout) :: Bi(4,0:n_B(1)+2,0:n_B(2)+2,0:n_B(3)+2)
    real(real64), intent(in)    :: h_B(3)
    real(real64), intent(in)    :: B0
    integer, intent(in)         :: B_dir

    integer :: ix, iy, iz
    real(real64) :: x, L, f

    L = max(h_B(1)*real(n_B(1),real64), 1.0e-12_real64)

    do iz = 0, n_B(3)+2
       do iy = 0, n_B(2)+2
          do ix = 0, n_B(1)+2
             x = real(ix-1, real64) * h_B(1)
             f = 1.0_real64 / (1.0_real64 + (x/L)**2)
             Bi(B_dir, ix, iy, iz) = Bi(B_dir, ix, iy, iz) + B0*f
          end do
       end do
    end do
  end subroutine PG_current

  !> Cusp-like placeholder localized at (x0,z0) with width dL
  subroutine EE_magnets(Bi, n_B, h_B, B0, x0, z0, dL)
    integer(int32), intent(in)  :: n_B(3)
    real(real64), intent(inout) :: Bi(4,0:n_B(1)+2,0:n_B(2)+2,0:n_B(3)+2)
    real(real64), intent(in)    :: h_B(3)
    real(real64), intent(in)    :: B0, x0, z0, dL

    integer :: ix, iy, iz
    real(real64) :: x, z, ax, az, g

    if (dL <= 0.0_real64) return

    do iz = 0, n_B(3)+2
       z  = real(iz-1, real64) * h_B(3)
       az = (z - z0)/dL
       do iy = 0, n_B(2)+2
          do ix = 0, n_B(1)+2
             x  = real(ix-1, real64) * h_B(1)
             ax = (x - x0)/dL
             g  = exp(-(ax*ax + az*az))
             Bi(1,ix,iy,iz) = Bi(1,ix,iy,iz) + B0 * (-2.0_real64*ax/dL) * g
             Bi(3,ix,iy,iz) = Bi(3,ix,iy,iz) + B0 * (+2.0_real64*az/dL) * g
          end do
       end do
    end do
  end subroutine EE_magnets

  !> Hall thruster placeholder: localized Bz around x0 (width dL)
  subroutine Bfield_Hall_thruster(Bi, n_B, h_B, B0, x0, dL)
    integer(int32), intent(in)  :: n_B(3)
    real(real64), intent(inout) :: Bi(4,0:n_B(1)+2,0:n_B(2)+2,0:n_B(3)+2)
    real(real64), intent(in)    :: h_B(3)
    real(real64), intent(in)    :: B0, x0, dL

    integer :: ix, iy, iz
    real(real64) :: x, a, g

    if (dL <= 0.0_real64) return

    do iz = 0, n_B(3)+2
       do iy = 0, n_B(2)+2
          do ix = 0, n_B(1)+2
             x = real(ix-1, real64) * h_B(1)
             a = (x - x0)/dL
             g = exp(-(a*a))
             Bi(3,ix,iy,iz) = Bi(3,ix,iy,iz) + B0*g
          end do
       end do
    end do
  end subroutine Bfield_Hall_thruster

end module mod_magneticField